import { Suspense } from "react";

import { ScreenIntro } from "@/app/(main)/dashboard/_components/screen-intro";
import { API_IN_BROWSER } from "@/lib/desk-api/flags";

import { StationsConsole } from "./_components/stations-console";

export default function Page() {
  return (
    <div className="flex flex-col gap-4">
      <ScreenIntro
        phase={2}
        eyebrow="Project operations · Station detail"
        title="One station: the unit, its power, what it consumed, what it accepts."
        achieves="The 3D unit, how power moves through it, the last 90 minutes, and the commands the management system accepts, every call shown."
        flow={{ id: "ops", step: "inspect" }}
        provenance={[
          {
            kind: "simulated",
            text: "All readings and command results are generated by a simulator standing in for the management system. Nothing here is connected to a live charger.",
          },
          {
            kind: "public",
            text: "The Lowell address comes from the public filing. Whether that station is commissioned is a Discovery question.",
          },
          ...(API_IN_BROWSER
            ? [
                {
                  kind: "simulated" as const,
                  text: "Hosted demo: the management-system endpoints are answered by the simulator running in this browser tab. The paths, methods and payloads are the ones a deployment would send to the real system.",
                },
              ]
            : []),
        ]}
      />
      <Suspense fallback={null}>
        <StationsConsole />
      </Suspense>
    </div>
  );
}
