import { ScreenIntro } from "@/app/(main)/dashboard/_components/screen-intro";
import { API_IN_BROWSER } from "@/lib/desk-api/flags";

import { StationsConsole } from "./_components/stations-console";

export default function Page() {
  return (
    <div className="flex flex-col gap-4">
      <ScreenIntro
        phase={2}
        eyebrow="Stations"
        title="Power checks and performance, over the station API."
        achieves="Each hybrid charger reports through the standard charge-point protocol, OCPP, to a management system that exposes an API. This screen reads that API every few seconds for solar production, battery state of charge, grid draw and charging output, runs a power check on demand that compares every reading to a threshold, and sends remote commands: start or stop a session, take a station out of service, reboot it, pull diagnostics. Every request and response is shown as it happens, so the integration is visible rather than implied. This is Phase 2 in the proposal because it depends on validated hardware interfaces and deployed units."
        provenance={[
          {
            kind: "simulated",
            text: "All readings and command results are generated by a simulator standing in for the management system. Nothing here is connected to a live charger.",
          },
          {
            kind: "public",
            text: "The Lowell address comes from the public filing. Whether that station is commissioned is a Discovery question.",
          },
          ...(API_IN_BROWSER
            ? [
                {
                  kind: "simulated" as const,
                  text: "Hosted demo: the management-system endpoints are answered by the simulator running in this browser tab. The paths, methods and payloads are the ones a deployment would send to the real system.",
                },
              ]
            : []),
        ]}
      />
      <StationsConsole />
    </div>
  );
}
