import { Suspense } from "react";

import { ScreenIntro } from "@/app/(main)/dashboard/_components/screen-intro";
import { API_IN_BROWSER } from "@/lib/desk-api/flags";

import { OperationsConsole } from "./_components/operations-console";

export default function Page() {
  return (
    <div className="flex flex-col gap-4">
      <ScreenIntro
        phase={2}
        eyebrow="Project operations · Locations"
        illustration={{
          src: "/media/site-commercial-v2.webp",
          alt: "A hybrid charger on a commercial forecourt",
          aspect: "16/9",
        }}
        flow={{ id: "ops", step: "locate" }}
        title="Every station on the map."
        achieves="Click a marker to open it."
        provenance={[
          {
            kind: "public",
            text: "The Lowell site and its address come from the public filing. Whether it is commissioned is a Discovery question.",
          },
          {
            kind: "sample",
            text: "The other six sites are illustrative placements on real public lots. Suryatech has not said where its units are or will be.",
          },
          {
            kind: "simulated",
            text: "All readings, sessions and revenue are generated by the station simulator. Revenue is delivered kWh times a sample tariff per site.",
          },
          ...(API_IN_BROWSER
            ? [
                {
                  kind: "simulated" as const,
                  text: "Hosted demo: the management-system endpoints are answered by the simulator running in this browser tab.",
                },
              ]
            : []),
        ]}
      />
      <Suspense fallback={null}>
        <OperationsConsole />
      </Suspense>
    </div>
  );
}
