import { format } from "date-fns";

import { ScreenIntro } from "@/app/(main)/dashboard/_components/screen-intro";
import { responseCards, responseColumns } from "@/data/boards";
import { mapcExportPack, mapcResponse } from "@/data/mapc-response";
import { buildObligations, sdpReportSchedule } from "@/data/obligations";
import { opportunities } from "@/data/opportunities";
import { buildDeadlineRows, upcomingDeadlines } from "@/lib/deadlines";
import { API_IN_BROWSER } from "@/lib/desk-api/flags";
import { scoreOpportunity } from "@/lib/fit";

import { type AttentionItem, OverviewLive } from "./_components/overview-live";

const toneClass: Record<string, string> = {
  navy: "bg-[#14284B]",
  gold: "bg-[#F2A900]",
  sky: "bg-sky-500",
  emerald: "bg-emerald-500",
  amber: "bg-amber-500",
  red: "bg-red-500",
  muted: "bg-slate-400",
};

export default function Page() {
  const now = new Date();
  const sdp = sdpReportSchedule(now);
  const rows = buildDeadlineRows(now);
  const upcoming = upcomingDeadlines(rows, 5);
  const obligations = buildObligations(now).filter((o) => o.id !== "veh122");
  const scored = opportunities.map((o) => scoreOpportunity(o));
  const chase = scored.filter((f) => f.verdict === "chase").length;
  const fields = mapcResponse.flatMap((t) => t.fields);
  const ready = fields.filter((f) => f.state === "ready").length;
  const missing = fields.filter((f) => f.state === "missing").length;
  const packReady = mapcExportPack.filter((f) => f.state === "ready").length;
  const packBlocked = mapcExportPack.filter((f) => f.state === "blocked").length;
  const openRequests = opportunities.filter((o) => o.status === "open").length;

  const prepAttention: AttentionItem[] = [
    ...rows
      .filter((r) => r.daysLeft !== null && r.daysLeft >= 0 && r.daysLeft <= 45)
      .map((r) => ({
        id: `dl-${r.id}`,
        severity: (r.daysLeft ?? 99) <= 14 ? ("critical" as const) : ("warning" as const),
        title: r.item,
        detail: `Due ${r.due}, ${r.daysLeft} days`,
        href: "/dashboard/deadlines",
      })),
    ...obligations
      .filter((o) => o.status === "confirm")
      .map((o) => ({
        id: `confirm-${o.id}`,
        severity: "info" as const,
        title: `Confirm filed: ${o.name}`,
        detail: "Past its date. Whether it was filed is unknown until Discovery.",
        href: "/dashboard/evidence",
      })),
    ...(packBlocked
      ? [
          {
            id: "pack-blocked",
            severity: "warning" as const,
            title: `${packBlocked} files blocked in the MAPC export pack`,
            detail: "Signatures and certificates not on file.",
            href: "/dashboard/export",
          },
        ]
      : []),
    ...(missing
      ? [
          {
            id: "fields-missing",
            severity: "info" as const,
            title: `${missing} fields missing in the MAPC response`,
            detail: `${ready} of ${fields.length} ready from the library.`,
            href: "/dashboard/assembler",
          },
        ]
      : []),
  ];

  const prepCounts = {
    watch: `${opportunities.length} seen · ${openRequests} open`,
    triage: `${chase} chase`,
    assemble: `${ready}/${fields.length} fields`,
    prove: `${obligations.length} filings`,
    export: `${packReady}/${mapcExportPack.length} files`,
    submit: "0 on record",
    report: `SDP in ${sdp.current.daysLeft} d`,
  };

  const prepNumbers = [
    {
      label: "Next filing",
      value: `${sdp.current.daysLeft} days`,
      tone:
        sdp.current.daysLeft <= 14
          ? ("critical" as const)
          : sdp.current.daysLeft <= 45
            ? ("warning" as const)
            : undefined,
    },
    { label: "Requests seen", value: String(opportunities.length) },
    { label: "Worth chasing", value: String(chase), tone: "ok" as const },
    {
      label: "Pack ready",
      value: `${packReady} / ${mapcExportPack.length}`,
      tone: packBlocked ? ("warning" as const) : undefined,
    },
  ];

  const cards = responseCards();
  const boardCounts = responseColumns.map((c) => ({
    title: c.title,
    count: cards.filter((k) => k.column === c.id).length,
    tone: toneClass[c.tone],
  }));

  return (
    <div className="flex flex-col gap-4">
      <ScreenIntro
        eyebrow="Overview"
        title={format(now, "EEEE, MMMM d, yyyy")}
        achieves="What needs attention, where each half of the business stands, and the next step in every flow."
        provenance={[
          {
            kind: "public",
            text: "Requests, closing dates and program rules come from COMMBUYS and mass.gov. The Lowell site comes from the public filing.",
          },
          {
            kind: "simulated",
            text: "Station readings, sessions, revenue and work orders are generated by the simulator. Six of the seven sites are illustrative placements.",
          },
          ...(API_IN_BROWSER
            ? [
                {
                  kind: "simulated" as const,
                  text: "Hosted demo: the station and fleet endpoints are answered by the simulator running in this browser tab.",
                },
              ]
            : []),
        ]}
      />
      <OverviewLive
        prepAttention={prepAttention}
        prepCounts={prepCounts}
        prepNumbers={prepNumbers}
        upcoming={upcoming}
        boardCounts={boardCounts}
      />
    </div>
  );
}
