import Link from "next/link";

import { format } from "date-fns";
import { ArrowUpRight } from "lucide-react";

import { PreparationKpis } from "@/app/(main)/dashboard/_components/preparation-kpis";
import { ScreenIntro } from "@/app/(main)/dashboard/_components/screen-intro";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { COMPANY } from "@/data/company";
import { daysUntil, sdpReportSchedule } from "@/data/obligations";
import { opportunities } from "@/data/opportunities";
import { buildDeadlineRows, upcomingDeadlines } from "@/lib/deadlines";
import { API_IN_BROWSER } from "@/lib/desk-api/flags";
import { scoreOpportunity } from "@/lib/fit";

import { OverviewOperations } from "./_components/overview-operations";
import { OverviewPreparation } from "./_components/overview-preparation";

export default function Page() {
  const now = new Date();
  const sdp = sdpReportSchedule(now);
  const scored = opportunities.map((o) => ({ opportunity: o, fit: scoreOpportunity(o) }));
  const worth = scored
    .filter((r) => r.fit.verdict !== "pass")
    .sort((a, b) => b.fit.score - a.fit.score)
    .slice(0, 4);

  return (
    <div className="flex flex-col gap-6">
      <ScreenIntro
        eyebrow="Overview"
        title={`Two halves of one business, on one screen. ${format(now, "EEEE, MMMM d, yyyy")}.`}
        achieves="Project operations first: where the stations stand, what they are putting out, how many cars charged today and what that earned. Package preparation second: what VEH122 asked for, what is due, and how far the next response is. Everything here is a summary that links to the section that owns it, so a morning starts on this page and ends wherever the number that moved sends you."
        provenance={[
          {
            kind: "public",
            text: "Requests, closing dates and program rules come from COMMBUYS and mass.gov. The Lowell site comes from the public filing.",
          },
          {
            kind: "simulated",
            text: "Station readings, sessions and revenue are generated by the simulator. Six of the seven sites are illustrative placements.",
          },
          ...(API_IN_BROWSER
            ? [
                {
                  kind: "simulated" as const,
                  text: "Hosted demo: the station and fleet endpoints are answered by the simulator running in this browser tab.",
                },
              ]
            : []),
        ]}
      />

      <section aria-labelledby="ops-heading" className="flex flex-col gap-3">
        <SectionHeading
          id="ops-heading"
          title="Project operations"
          phase={2}
          blurb="Locations, power, performance, cars charged, revenue."
          href="/dashboard/operations"
          cta="Locations map"
        />
        <OverviewOperations />
      </section>

      <section aria-labelledby="prep-heading" className="flex flex-col gap-3">
        <SectionHeading
          id="prep-heading"
          title="Package preparation"
          phase={1}
          blurb="Requests, deadlines, the response and its evidence."
          href="/dashboard/deadlines"
          cta="Deadline board"
        />
        <PreparationKpis
          sdpDaysLeft={sdp.current.daysLeft}
          sdpDue={format(sdp.current.due, "MMM d, yyyy")}
          sdpQuarter={sdp.current.label}
          seen={opportunities.length}
          awarded={opportunities.filter((o) => o.status === "bid-to-po").length}
          chase={scored.filter((r) => r.fit.verdict === "chase").length}
          contractDaysLeft={daysUntil(COMPANY.contractEnd, now)}
        />
        <OverviewPreparation upcoming={upcomingDeadlines(buildDeadlineRows(now), 5)} worth={worth} />
      </section>
    </div>
  );
}

function SectionHeading({
  id,
  title,
  phase,
  blurb,
  href,
  cta,
}: {
  id: string;
  title: string;
  phase: 1 | 2;
  blurb: string;
  href: string;
  cta: string;
}) {
  return (
    <div className="flex flex-wrap items-end justify-between gap-2 border-b pb-2">
      <div className="flex items-center gap-2">
        <h2 id={id} className="font-medium text-lg tracking-tight">
          {title}
        </h2>
        <Badge variant="outline" className="h-auto rounded-sm px-1.5 py-0 text-[10px] uppercase tracking-wider">
          Phase {phase}
        </Badge>
        <span className="hidden text-muted-foreground text-sm sm:inline">{blurb}</span>
      </div>
      <Button variant="ghost" size="sm" asChild>
        <Link prefetch={false} href={href}>
          {cta}
          <ArrowUpRight data-icon="inline-end" />
        </Link>
      </Button>
    </div>
  );
}
