import { ScreenIntro } from "@/app/(main)/dashboard/_components/screen-intro";
import { API_IN_BROWSER } from "@/lib/desk-api/flags";

import { RevenueConsole } from "./_components/revenue-console";

export default function Page() {
  return (
    <div className="flex flex-col gap-4">
      <ScreenIntro
        phase={2}
        eyebrow="Project operations · Sessions and revenue"
        illustration={{ src: "/media/site-park-v2.webp", alt: "A hybrid charger at a state park lot", aspect: "16/9" }}
        flow={{ id: "ops", step: "bill" }}
        title="Cars, energy, revenue."
        achieves="Today and the last 30 days, per station."
        provenance={[
          {
            kind: "simulated",
            text: "Sessions, energy and uptime are generated by the station simulator with a deterministic 30-day history. Nothing here is a real transaction.",
          },
          {
            kind: "sample",
            text: "Tariffs per site are assumptions between $0.35 and $0.42 per kWh. Suryatech has not shared its pricing or its billing platform.",
          },
          ...(API_IN_BROWSER
            ? [
                {
                  kind: "simulated" as const,
                  text: "Hosted demo: the fleet endpoints are answered by the simulator running in this browser tab.",
                },
              ]
            : []),
        ]}
      />
      <RevenueConsole />
    </div>
  );
}
