import { ScreenIntro } from "@/app/(main)/dashboard/_components/screen-intro";
import { API_IN_BROWSER } from "@/lib/desk-api/flags";

import { RevenueConsole } from "./_components/revenue-console";

export default function Page() {
  return (
    <div className="flex flex-col gap-4">
      <ScreenIntro
        phase={2}
        eyebrow="Project operations · Sessions and revenue"
        title="Cars charged, energy delivered, and what it earned."
        achieves="The operating side in money: how many vehicles the fleet charged today and over the last thirty days, how much energy that was, what it billed at each site's tariff, and how much of the month each station was available to sell. This is the page a buyer's O&M clause (category 4 of VEH122) asks Suryatech to report on, and the page that tells Mayur which sites pay for themselves."
        provenance={[
          {
            kind: "simulated",
            text: "Sessions, energy and uptime are generated by the station simulator with a deterministic 30-day history. Nothing here is a real transaction.",
          },
          {
            kind: "sample",
            text: "Tariffs per site are assumptions between $0.35 and $0.42 per kWh. Suryatech has not shared its pricing or its billing platform.",
          },
          ...(API_IN_BROWSER
            ? [
                {
                  kind: "simulated" as const,
                  text: "Hosted demo: the fleet endpoints are answered by the simulator running in this browser tab.",
                },
              ]
            : []),
        ]}
      />
      <RevenueConsole />
    </div>
  );
}
